version: '3'

includes:
  ansible: 
    taskfile: ./ansible
    dir: ./ansible
  compose: 
    taskfile: ./compose
    dir: ./compose
  k8s:
    taskfile: ./k8s
    dir: ./k8s

tasks:

  default:
    silent: true
    cmd: task --list
