- name: APT hosts
  hosts: apt
  become: true
  tasks:

    - name: Install desired package
      ansible.builtin.apt:
        pkg:
        - tmux
        - golang
        - lazygit

- name: DNF hosts
  hosts: dnf
  become: true
  tasks:

    - name: Install desired package
      ansible.builtin.dnf:
        state: latest
        name:
          - tmux
          - golang
          # - lazygit
