- name: tmuxlab
  hosts: linux
  become: true
  tasks:

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: ./../../common/tmuxlab.sh
      dest: /usr/local/bin/tmuxlab
      mode: u+x,g+x,o+x
