- name: APT hosts
  hosts: apt
  tasks:

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache is valid for 1 hour

    - name: Upgrade all packages
      become: true
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes

- name: DNF hosts
  hosts: dnf
  become: true
  tasks:

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
