version: '3'

vars:
  inventory: inventory/inventory.yaml

tasks:

  default:
    silent: true
    cmd: task --list

  inv:
    desc: Test inventory
    summary: Check that the inventory file is configured correctly
    cmd: ansible-inventory -i {{.inventory}} --list

  ping:
    desc: Ping all the hosts
    summary: Check that all the hosts are reachable 
    cmds: 
      - for: ['linux']
        cmd: ansible {{.ITEM}} -m ping -i {{.inventory}}

  update:
    desc: Update hosts
    summary: Update all the installed packages using the pakcage manager
    cmd: ansible-playbook -i {{.inventory}} playbooks/update.yaml
  
  install:
    desc: Install desired software
    summary: |
      Install the desired list of softwares
      Manages also the repositories configurations
    cmd: ansible-playbook -i {{.inventory}} playbooks/install.yaml

  tmuxlab:
    desc: Render tmuxlab system wide available 
    summary: |
      By placing the script tmuxlab into the folder /usr/local/bin/ make it available systemwide
      Launch it by simply typing tmuxlab
      Used to launch a tmux session calibrated to managing the homelab
    cmd: ansible-playbook -i {{.inventory}} playbooks/tmuxlab.yaml
